spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/groupdb
    username: groupadmin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: group-service
  kafka:
    producer:
      properties:
        spring.json.remove.type.headers: true

server:
  port: 8082

# Kafka config
spring.kafka.bootstrap-servers: localhost:9092
